### PR TITLE
Munky python3

### PR DESCRIPTION
**Pull request by LcTrKiD**
I've tested the middleware with Munki 3.6.2.3776 and Munki 3.7.0.3855 (Embedded python) and works as expected

### CODE REVIEW

**Comment by g4fa** [comment]
Hi

When I try to compile Munki 3.7.0.3855 , I have this error 
productbuild: error: No URL for pkg-ref "com.googlecode.munki.python".
Error creating /Users/fabien/munkitools-3.7.0.3857.pkg.
Attempting to clean up temporary files...

Can you help me ?

**Comment by LcTrKiD** [comment]
You can download that version here: https://www.dropbox.com/s/t81086iwjyh89fp/munkitools-3.7.0.3855.pkg?dl=1

**Comment by g4fa** [comment]
Hi

Can you please reforward me munkitools 3.7.0  ?

Thanks

**Comment by clburlison** [comment]
@LcTrKiD I think changes to this script should be backwards compatible. 
Something like:
```python
try:
    from string import maketrans
    from OpenSSL.crypto import FILETYPE_PEM
    from OpenSSL.crypto import load_privatekey
    from OpenSSL.crypto import sign
except:
    from rsa import PrivateKey, sign
```

Or we could check for the python version 

```python
    if PY_VER[0] == 2:
       fooo
    else if PY_VER[0] == 3:
       bar
```

But don't do anything without @AaronBurchfield's input. 

@g4fa Please see the munki-dev list https://groups.google.com/forum/#!topic/munki-dev/k5nCLZHI0nA

**Comment by AaronBurchfield** [comment]
I've added support for python3 slightly differently to _hopefully_ make it easier to remove the py2 code later. Please check out the [`v2-python3`](https://github.com/AaronBurchfield/CloudFront-Middleware/tree/v2-python3) branch and give it a test.

@LcTrKiD thank you so much for working on this!

**Pull request closed without merging**
